version: "2"
run:
    timeout: 5m
    go: 1.26.0
    build-tags:
        - goexperiment.arenas
        - goexperiment.goroutineleakprofile
        - goexperiment.jsonv2
        - goexperiment.runtimesecret
        - goexperiment.simd
    allow-parallel-runners: true
    allow-serial-runners: true
output:
    formats: {}
linters:
    enable:
        - bodyclose
        - contextcheck
        - copyloopvar
        - cyclop
        - dupl
        - durationcheck
        - errcheck
        - errchkjson
        - errname
        - errorlint
        - exhaustive
        - forbidigo
        - forcetypeassert
        - ginkgolinter
        - gochecksumtype
        - gocritic
        - gocyclo
        - godot
        - gosec
        - gosmopolitan
        - govet
        - ineffassign
        - interfacebloat
        - intrange
        - loggercheck
        - maintidx
        - mirror
        - misspell
        - musttag
        - nakedret
        - nilerr
        - nilnesserr
        - nilnil
        - noctx
        - nolintlint
        - perfsprint
        - predeclared
        - protogetter
        - reassign
        - staticcheck
        - testifylint
        - unconvert
        - unused
        - usetesting
        - wastedassign
        - zerologlint
    settings:
        godot:
            require-expecting-newline: false
        gosec:
            excludes:
                - G102
                - G104
                - G301
                - G304
                - G306
                - G307
                - G404
        cyclop:
            max-complexity: 25
        gocyclo:
            min-complexity: 25
        gocritic:
            disabled-checks:
                - ifElseChain
                - sloppyReassign
formatters:
    enable:
        - gci
        - goimports
        - gofumpt
        - golines
issues:
    max-issues-per-linter: 100
    max-same-issues: 5
    exclude-rules:
        - path: _test\.go
          linters:
            - exhaustruct
            - funlen
            - goconst
            - gocognit
            - nestif
            - paralleltest
            - prealloc
            - thelper
            - unparam
            - gochecknoglobals
            - gochecknoinits
            - recvcheck
            - wrapcheck
