package pipeline

import (
	"errors"
	"testing"
	"testing/fstest"

	"github.com/LarsArtmann/gogenfilter/v3"
	"github.com/larsartmann/go-finding"
)

func TestGeneratedFileFilter_Disabled(t *testing.T) {
	t.Parallel()

	gf, err := NewGeneratedFileFilter(nil)
	if err != nil {
		t.Fatalf("NewGeneratedFileFilter() error = %v", err)
	}

	findings := []finding.Finding{
		{ID: "1", Position: finding.Position{File: "a.go"}},
		{ID: "2", Position: finding.Position{File: "b.go"}},
	}

	result, err := gf.Process(t.Context(), findings)
	if err != nil {
		t.Fatalf("Process() error = %v", err)
	}

	if len(result) != 2 {
		t.Fatalf("Process() = %d findings, want 2", len(result))
	}
}

func TestGeneratedFileFilter_FiltersGeneratedFiles(t *testing.T) {
	t.Parallel()

	fsys := fstest.MapFS{
		"gen/mock.go":      {Data: []byte("// Code generated by mockgen. DO NOT EDIT.\npackage main\n")},
		"gen/query.sql.go": {Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage main\n")},
		"cmd/main.go":      {Data: []byte("package main\n\nfunc main() {}\n")},
	}

	opt, err := gogenfilter.WithFilterOptions(gogenfilter.FilterAll)
	if err != nil {
		t.Fatalf("WithFilterOptions() error = %v", err)
	}

	gf, err := NewGeneratedFileFilter(
		nil,
		opt,
		gogenfilter.WithFS(fsys),
	)
	if err != nil {
		t.Fatalf("NewGeneratedFileFilter() error = %v", err)
	}

	findings := []finding.Finding{
		{ID: "1", Position: finding.Position{File: "gen/mock.go"}},
		{ID: "2", Position: finding.Position{File: "gen/query.sql.go"}},
		{ID: "3", Position: finding.Position{File: "cmd/main.go"}},
		{ID: "4", Position: finding.Position{File: ""}},
	}

	result, err := gf.Process(t.Context(), findings)
	if err != nil {
		t.Fatalf("Process() error = %v", err)
	}

	if len(result) != 2 {
		t.Fatalf("Process() = %d findings, want 2", len(result))
	}

	ids := make([]string, len(result))
	for i, f := range result {
		ids[i] = f.ID
	}

	want := []string{"3", "4"}
	if !sliceEqual(ids, want) {
		t.Fatalf("Process() IDs = %v, want %v", ids, want)
	}
}

func TestGeneratedFileFilter_FiltersSpecificGenerator(t *testing.T) {
	t.Parallel()

	// FilterSQLC only matches specific sqlc filename patterns (query.sql.go, .sql.go, etc.)
	fsys := fstest.MapFS{
		"db/query.sql.go": {Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n")},
		"db/mock.go":      {Data: []byte("// Code generated by mockgen. DO NOT EDIT.\npackage db\n")},
		"cmd/main.go":     {Data: []byte("package main\n\nfunc main() {}\n")},
	}

	opt, err := gogenfilter.WithFilterOptions(gogenfilter.FilterSQLC)
	if err != nil {
		t.Fatalf("WithFilterOptions() error = %v", err)
	}

	gf, err := NewGeneratedFileFilter(
		nil,
		opt,
		gogenfilter.WithFS(fsys),
	)
	if err != nil {
		t.Fatalf("NewGeneratedFileFilter() error = %v", err)
	}

	findings := []finding.Finding{
		{ID: "1", Position: finding.Position{File: "db/query.sql.go"}},
		{ID: "2", Position: finding.Position{File: "db/mock.go"}},
		{ID: "3", Position: finding.Position{File: "cmd/main.go"}},
	}

	result, err := gf.Process(t.Context(), findings)
	if err != nil {
		t.Fatalf("Process() error = %v", err)
	}

	if len(result) != 2 {
		t.Fatalf("Process() = %d findings, want 2", len(result))
	}

	ids := make([]string, len(result))
	for i, f := range result {
		ids[i] = f.ID
	}

	want := []string{"2", "3"}
	if !sliceEqual(ids, want) {
		t.Fatalf("Process() IDs = %v, want %v", ids, want)
	}
}

func TestGeneratedFileFilter_NewFilterError(t *testing.T) {
	t.Parallel()

	_, err := NewGeneratedFileFilter(
		nil,
		func(_ *gogenfilter.Filter) error {
			return errTestConfigError
		},
	)
	if err == nil {
		t.Fatal("NewGeneratedFileFilter() expected error, got nil")
	}
}

func TestGeneratedFileFilter_Name(t *testing.T) {
	t.Parallel()

	gf, _ := NewGeneratedFileFilter(nil)
	if gf.Name() != "generated-file-filter" {
		t.Fatalf("Name() = %q, want %q", gf.Name(), "generated-file-filter")
	}
}

func TestGeneratedFileFilter_KeepOnMissingFile(t *testing.T) {
	t.Parallel()

	fsys := fstest.MapFS{}

	opt, err := gogenfilter.WithFilterOptions(gogenfilter.FilterAll)
	if err != nil {
		t.Fatalf("WithFilterOptions() error = %v", err)
	}

	gf, err := NewGeneratedFileFilter(
		nil,
		opt,
		gogenfilter.WithFS(fsys),
	)
	if err != nil {
		t.Fatalf("NewGeneratedFileFilter() error = %v", err)
	}

	findings := []finding.Finding{
		{ID: "1", Position: finding.Position{File: "missing.go"}},
	}

	result, err := gf.Process(t.Context(), findings)
	if err != nil {
		t.Fatalf("Process() error = %v", err)
	}

	if len(result) != 1 {
		t.Fatalf("Process() = %d findings, want 1", len(result))
	}

	if result[0].ID != "1" {
		t.Fatalf("Process() ID = %q, want %q", result[0].ID, "1")
	}
}

func sliceEqual(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}

	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}

	return true
}

var errTestConfigError = errors.New("test config error")
